---
title: "HW 4 Problem 2"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
--- 

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
```{r, echo=FALSE}
data_restaurants = rest_inspec
  
data_restaurants %>%
count(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B
```{r, echo=FALSE}
box_plot = 
  data_restaurants %>%
  mutate(boro = fct_reorder(boro, score)) %>%
  filter(boro != "Missing") %>%
  drop_na(score) %>%
  ggplot(aes(x = boro, y = score, fill = boro)) + 
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Boxplot of Scores in Each Borough"
  ) 

ggplotly(box_plot)
  
```

### Chart C

```{r, echo=FALSE}
thai_plot = 
  data_restaurants %>%
  filter(cuisine_description == "Thai") %>%
  filter(boro == "MANHATTAN") %>%
  filter(critical_flag == "Critical") %>%
  ggplot(aes(x = zipcode, fill = zipcode)) + 
  geom_histogram(binwidth = 2) + 
  labs(
    title = "Critical Thai Restaurants in Manhattan by Zipcode"
  ) 

ggplotly(thai_plot)

```
